version: '2'
services:
  webserver:
    build: ./docker/php
    links:
    - database
    ports:
    - "8081:80"
    volumes:
    - ./config/apache2/sites-enabled:/etc/apache2/sites-enabled
    - ./src/:/var/www/html
    - ./config/php/:/usr/local/etc/php/
    - ./config/ComicLib/:/var/www/ComicLibConfig/
    - ./config/ImageMagick/policy.xml:/etc/ImageMagick-6/policy.xml # Increase RAM for Image Magick to 2GB.
    command: bash -c "source /etc/apache2/envvars; apache2 -D FOREGROUND"
  database:
    image: mysql:5.5
#    Open Port for development.
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}