version: '2'
services:
  webserver:
    build: ./docker/php
    links:
    - database
    ports:
    - "8081:80"
    volumes:
    - ./config/apache2/sites-enabled:/etc/apache2/sites-enabled
    - ./src/:/var/www/html
    - ./config/php/:/usr/local/etc/php/
    environment:
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
    command: bash -c "htpasswd -Bb -c /etc/apache2/.htpasswd $${AUTH_USERNAME} $${AUTH_PASSWORD}; source /etc/apache2/envvars; apache2 -D FOREGROUND"
  database:
    image: hypriot/rpi-mysql:5.5
    volumes:
      - ./mysql-data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
